### PR TITLE
:seedling: Add more links to ignore file

### PR DESCRIPTION
**Pull request by peppi-lotta**
Link checker is giving some false positives. I suggest we add links to ignore file to avoid these false positives. 

## Fixes 
Fixes: #527
Fixes: #528

### CODE REVIEW

**Comment by tuminoid** [comment]
To get issues marked as solved and auto close, use syntax:

Fixes: #number 
Fixes: #another 

It does not understand your nicely formatted summary :)

**Review by tuminoid — COMMENTED** [review]
/lgtm

**Review by smoshiur1237 — COMMENTED** [review]
/approve

**Review by lentzi90 — COMMENTED** [review]
/approve

**Pull request merged**
