### PR TITLE
Update try-it.md based on #277 in dev-env

### PR DESCRIPTION
**Pull request by fmuyassarov**
Update try-it.md based on [#277](https://github.com/metal3-io/metal3-dev-env/pull/277) in Metal3-dev-env.

### CODE REVIEW

**Comment by iranzo** [comment]
> /cc @iranzo

Hi,
I was moved to another team so I would not be fair to review it :-) 

'cluster cluste' ?

image


Regards,
Pablo

**Comment by fmuyassarov** [comment]
> > /cc @iranzo
> 
> Hi,
> I was moved to another team so I would not be fair to review it :-)
> 
> 'cluster cluste' ?
> 
> image
> 
> Regards,
> Pablo

Hi, 
Good catch. Thanks

**Comment by fmuyassarov** [comment]
> Why is there an image change in this PR ?

Because I added Kind to the Management cluster.
kind

**Comment by maelk** [comment]
In the case of Kind, it is not a libvirt VM

**Comment by fmuyassarov** [comment]
> In the case of Kind, it is not a libvirt VM

Ops, nice catch. Will update it. Thanks

**Comment by fmuyassarov** [comment]
[#293](https://github.com/metal3-io/metal3-dev-env/pull/293) was merged. Canceling hold
/hold cancel

**Comment by maelk** [comment]
you seem to have a commit "Rebase". Can you please make your commit message more explicit, or if it is actually a rebase, then only change your first commit. thank you

**Comment by fmuyassarov** [comment]
> you seem to have a commit "Rebase". Can you please make your commit message more explicit, or if it is actually a rebase, then only change your first commit. thank you

I hope it is okay now

**Comment by fmuyassarov** [comment]
This changes + others are done in [#180](https://github.com/metal3-io/metal3-io.github.io/pull/180)

**Pull request closed without merging**
