### PR TITLE
.github: secure github actions

### PR DESCRIPTION
**Pull request by tuminoid**
Set top-level permissions to read, only allowing write where necessary.

Pin actions by a sha.

### CODE REVIEW

**Comment by tuminoid** [comment]
/hold

Holding for possible further changes.

**Comment by tuminoid** [comment]
/unhold

@kashifest  please do the branch magic for this one as well

**Review by kashifest — APPROVED** [review]

**Review by lentzi90 — APPROVED** [review]
/approve

**Pull request merged**
