### PR TITLE
Added KUBERNETES_BINARIES_VERSION and related files version environmental variables

### PR DESCRIPTION
**Pull request by Xenwar**
Adds `KUBERNETES_BINARIES_VERSION` variable that determines what version of kubelet, kubeadm and kubectl is installed.

Also added `KUBERNETES_BINARIES_CONFIG_VERSION` for kubelet.service and 10-kubeadm.conf systemd files.

### CODE REVIEW

**Comment by iranzo** [comment]
Don't worry about the external link failing, we're checking that in parallel

**Comment by maelk** [comment]
please update the PR name and description with the actual name of the variable

**Pull request merged**
