### PR TITLE
Dark mode feature

### PR DESCRIPTION
**Pull request by SafeEHA**
Creating a dark  mode feature for metal3 website

cc: @Rozzii @elfosardo @hroyrh

### CODE REVIEW

**Comment by SafeEHA** [comment]
@Rozzii please can you give me some guidance on how to fix this error

**Comment by SafeEHA** [comment]
@Rozzii this has been fixed, kindly review

**Comment by Rozzii** [comment]
@SafeEHA  could you please make the highlighted text a bit more readable.
This is how it looks like to me with the dark mode 
image
And this is how it should look IMO:
image

**Review by Rozzii — CHANGES_REQUESTED** [review]
As mentioned in previous comment.

**Comment by SafeEHA** [comment]
Hi @Rozzii 
I have fixed the issue i believe, kindly review if there's anything else, thanks

**Review by Rozzii — APPROVED** [review]

**Review by lentzi90 — COMMENTED** [review]
Nice!
Could you fix the icons on the blog page?

Screenshot from 2023-09-25 14-30-58
Compare with
image

**Comment by SafeEHA** [comment]
@lentzi90 i have made the icons visisble, please check it out

**Review by lentzi90 — COMMENTED** [review]
Thanks!
/approve

**Comment by tuminoid** [comment]
Can we do something to the CNCF logo, it looks horrible in dark mode?

**Comment by lentzi90** [comment]
> Can we do something to the CNCF logo, it looks horrible in dark mode?

Do you mean this one?
image

I don't know, to me it does not look so bad :sweat_smile:  
CNCF has different color logos though that we can use. For example
image
from [here](https://www.cncf.io/).

**Comment by SafeEHA** [comment]
Thanks @lentzi90 
I'll try to find the image you've referenced and use it instead

**Comment by lentzi90** [comment]
This is where to find them: https://github.com/cncf/artwork/blob/master/examples/other.md#cncf-logos
I should have linked there directly

**Comment by SafeEHA** [comment]
This is perfect thank you!

**Comment by SafeEHA** [comment]
@lentzi90 @tuminoid 
I've fixed the image, kindly review

**Comment by tuminoid** [comment]
> @lentzi90 @tuminoid I've fixed the image, kindly review

Much better, thank you.

**Comment by lentzi90** [comment]
Nice!
I see our pre-commit hook is a bit nit picky... It want's newlines at the end of the `.svg` files :roll_eyes: 
Could you please try to open them in a text editor and add the newline?

**Comment by SafeEHA** [comment]
I just fixed that but it seems there's a merge conflict in the commit and i don't know how to get to it 
@lentzi90

**Comment by lentzi90** [comment]
It looks like your branch is quite far behind unfortunately (27 commits!). :slightly_frowning_face:  Untangling that merge conflict could be tricky and I'm not sure I can help with it. Another option could be to just "start over", i.e. grab the latest code and then try to "redo" what you have done in this PR. That could be significantly easier I hope, since you already have the code and can copy/paste parts of it at least.

**Comment by SafeEHA** [comment]
A new PR https://github.com/metal3-io/metal3-io.github.io/pull/363 has been created for this feature

**Pull request closed without merging**
