### PR TITLE
adding blogpost about the conference OpenStack-Ironic-and-Bare-Metal-…

### PR DESCRIPTION
**Pull request by ptrnull**
…Infrastructure_All-Abstractions-Start-Somewhere

Converts the media link to that event in a blogpost as discussed in https://github.com/metal3-io/metal3-io.github.io/issues/73

Date of publication: 31/10/2019

Signed-off-by: Pedro Ibáñez <pedro@redhat.com>

### CODE REVIEW

**Comment by iranzo** [comment]
@russellb @dhellmann I don't have permissions to retry the travis build and it's not configured for allowing posts in the future, can you please retrigger so that it passes the build and you can then merge if ok?

**Comment by iranzo** [comment]
> /retest

alternatively you can force-push  a rebase of your branch so that travis will-retrigger

**Comment by dhellmann** [comment]
> /retest

This doesn't seem to have done anything, but going to the Travis UI via the Details link on this page showed me a button to rerun the build from there.

**Comment by iranzo** [comment]
> > /retest
> 
> This doesn't seem to have done anything, but going to the Travis UI via the Details link on this page showed me a button to rerun the build from there.

As we're not 'admins' of this repo, we can't go to that page and do the 'rebuild' (if not, travis would have shown the rebuild or retrigger for us too)

**Pull request merged**
