### PR TITLE
Disable line numbers

### PR DESCRIPTION
**Pull request by iranzo**
Signed-off-by: Pablo Iranzo Gómez <Pablo.Iranzo@gmail.com>

### CODE REVIEW

**Comment by fmuyassarov** [comment]
Can you please add a link  to the rendered html?

**Comment by iranzo** [comment]
> Can you please add a link to the rendered html?

It's always in the 'details' for 'netlify/metal3/deploy-preview', in this case a sample article: https://deploy-preview-148--metal3.netlify.com/blog/2019/09/11/baremetal-operator

**Pull request merged**
