### PR TITLE
Use try-it as a full-featured markdown file

### PR DESCRIPTION
**Pull request by iranzo**
Make try-it a full featured document with admonitions, copy on code blocks, etc

- Site documents start with heading level '2', that's one of the changes
- Extra comments above/below is for vscode extension that updates TOC automatically on document save 
- Note converted to 'warning' and another Note to 'info' using admonitions like in articles
- Code blocks now feature 'copy' like any article code block

PR Rendered at: https://deploy-preview-149--metal3.netlify.com/try-it.html

### CODE REVIEW

**Comment by iranzo** [comment]
@fmuyassarov aside that the image path, what do you think about the idea?

**Comment by iranzo** [comment]
> I think you need to change the path to the image
> ``

Fixed

**Comment by fmuyassarov** [comment]
> @fmuyassarov aside that the image path, what do you think about the idea?

Personally, it looks nice to me. Just one minor comment, is this (##instructions) how is it suppose to look?

inst

**Comment by fmuyassarov** [comment]
> > @fmuyassarov aside that the image path, what do you think about the idea?
> 
> Personally, it looks nice to me. Just one minor comment, is this (##instructions) how is it suppose to look?
> 
> inst

Ah, seems okay in the HTML, sorry

**Comment by iranzo** [comment]
> > > @fmuyassarov aside that the image path, what do you think about the idea?
> > 
> > 
> > Personally, it looks nice to me. Just one minor comment, is this (##instructions) how is it suppose to look?
> > inst
> 
> Ah, seems okay in the HTML, sorry

Yes, it's rendered at https://deploy-preview-149--metal3.netlify.com/try-it.html
imagen

**Comment by iranzo** [comment]
Also, if you scroll down to 'warning' and 'note' you'll see the admonitions formatting for that piece of code

**Comment by fmuyassarov** [comment]
Well done🎉, lgtm.
Just one general question, I know it isn't this PR that changed that, but why is there some space between the line numbers and commands next to them?

space

**Comment by iranzo** [comment]
It's a problem with the formatting, the plan is to get #148  merged and get some feedback from Matt who did the design to help on this topic with the CSS.

**Comment by fmuyassarov** [comment]
> It's a problem with the formatting, the plan is to get #148 merged and get some feedback from Matt who did the design to help on this topic with the CSS.

Ok, thanks

**Comment by iranzo** [comment]
PD: the preview doesn't update when other things are merged until rebase is done, just FYI

**Pull request merged**
