### PR TITLE
Update try it guide

### PR DESCRIPTION
**Pull request by lentzi90**
- Fix some spelling and update the dictionary. I'm a bit disturbed that I had to put `"tl"` and `"dr"` as separate words to get it to accept `tl;dr`. Do you know if there is a better way to do this?
- Removed non-existing section from TOC
- Added section for tear down to make it easier to find. I'm wondering if it would make sense to put this as a level 2 section at the end instead? Then we would have 1) Environment setup 2) Working with environment 3) Tear down environment. What do you think?
- Updated logs example to use the new deployment name.

### CODE REVIEW

**Review by fmuyassarov — COMMENTED** [review]
/lgtm
thank you!

**Comment by jan-est** [comment]
In [2.5. Running Custom Cluster API Provider Metal3](https://github.com/metal3-io/metal3-io.github.io/blob/c4c8d68ad0bd007a95717afc38aa0bbc7b3b8fad/try-it.md#25-running-custom-cluster-api-provider-metal3)  the instruction is to scale down the statefulset: 
`kubectl scale statefulset capm3-controller-manager -n capm3-system --replicas=0` 

I am wondering why we should scale down statefulset instead of deployment? I think the procedure should be same that it is in [2.4](https://github.com/metal3-io/metal3-io.github.io/blob/c4c8d68ad0bd007a95717afc38aa0bbc7b3b8fad/try-it.md#24-running-custom-baremetal-operator).

**Comment by lentzi90** [comment]
> In [2.5. Running Custom Cluster API Provider Metal3](https://github.com/metal3-io/metal3-io.github.io/blob/c4c8d68ad0bd007a95717afc38aa0bbc7b3b8fad/try-it.md#25-running-custom-cluster-api-provider-metal3) the instruction is to scale down the statefulset:
> `kubectl scale statefulset capm3-controller-manager -n capm3-system --replicas=0`
> 
> I am wondering why we should scale down statefulset instead of deployment? I think the procedure should be same that it is in [2.4](https://github.com/metal3-io/metal3-io.github.io/blob/c4c8d68ad0bd007a95717afc38aa0bbc7b3b8fad/try-it.md#24-running-custom-baremetal-operator).

Well spotted! I think you are correct that this should be deployment in both places.
For reference this is all deployments and statefulsets I can find:
```console
$ kubectl get deploy,sts -A
NAMESPACE                           NAME                                                            READY   UP-TO-DATE   AVAILABLE   AGE
capi-kubeadm-bootstrap-system       deployment.apps/capi-kubeadm-bootstrap-controller-manager       1/1     1            1           56m
capi-kubeadm-control-plane-system   deployment.apps/capi-kubeadm-control-plane-controller-manager   1/1     1            1           56m
capi-system                         deployment.apps/capi-controller-manager                         1/1     1            1           56m
capi-webhook-system                 deployment.apps/capi-controller-manager                         1/1     1            1           56m
capi-webhook-system                 deployment.apps/capi-kubeadm-bootstrap-controller-manager       1/1     1            1           56m
capi-webhook-system                 deployment.apps/capi-kubeadm-control-plane-controller-manager   1/1     1            1           56m
capi-webhook-system                 deployment.apps/capm3-controller-manager                        1/1     1            1           56m
capi-webhook-system                 deployment.apps/capm3-ipam-controller-manager                   1/1     1            1           56m
capm3-system                        deployment.apps/capm3-baremetal-operator-controller-manager     1/1     1            1           56m
capm3-system                        deployment.apps/capm3-controller-manager                        1/1     1            1           56m
capm3-system                        deployment.apps/capm3-ipam-controller-manager                   1/1     1            1           56m
cert-manager                        deployment.apps/cert-manager                                    1/1     1            1           57m
cert-manager                        deployment.apps/cert-manager-cainjector                         1/1     1            1           57m
cert-manager                        deployment.apps/cert-manager-webhook                            1/1     1            1           57m
kube-system                         deployment.apps/coredns                                         2/2     2            2           57m
local-path-storage                  deployment.apps/local-path-provisioner                          1/1     1            1           57m
```

As you can see there is no statefulset so it should probably be deployment. It also looks like the `bare-metal-operator` should be changed to `capm3-baremetal-operator-controller-manager`. Will update the PR. :slightly_smiling_face:

**Comment by dtantsur** [comment]
I'd probably avoid using "tl;dr" in the official documentation

**Review by fmuyassarov — COMMENTED** [review]
/lgtm
/assign @hroyrh

**Pull request merged**
