### PR TITLE
change OWNERS file to reflect team changes

### PR DESCRIPTION
**Pull request by Rozzii**

### CODE REVIEW

**Comment by Rozzii** [comment]
I am currently updating the OWNER files in the Metal3 repositories please comment if you feel that your removal or addition as an approver or reviewer is not correct or if you have any additional comments.

/cc @iranzo @hardys @knowncitizen @stbenjam @fmuyassarov 

Would you like to stay as an approver @matthewcarleton ?

**Comment by matthewcarleton** [comment]
I think I can be removed

**Comment by knowncitizen** [comment]
Feel free to remove me. Thanks.

**Comment by kashifest** [comment]
Fore merging it since this has been agreed before.

**Pull request merged**
