### PR TITLE
Metal3 kubecon 2k19 blogpost

### PR DESCRIPTION
**Pull request by ptrnull**
Blogpost about the Metal3 talk and video from the KubeCon NA 2019

/cc @russellb 
/cc @dhellmann 

Publication date is set to 2019-12-04 for having some time to review.

### CODE REVIEW

**Comment by russellb** [comment]
lgtm, though check out the failure from travis-ci

**Comment by iranzo** [comment]
> lgtm, though check out the failure from travis-ci

It fails because netlify does render in the future (as we defined it to do so) but travis does check only for 'actual articles' as the article is dated for 4th december, it will fail on travis because of the link at docs pointing to it because the files is still not rendered.

We can make travis not to fail by adjusting runtime testing but this will not show (or shouldn't) appear on the website.

We've a pending change to build the website on travis and then pushing the 'rendered' one insted of using GH Rendering so that we can, among other things:

- Use scheduled posts that just 'appear' on the date they are expected
- Use admonitions and other plugins that makes richer webpage

If you retrigger on 4th december, the test will pass and you could merge

**Comment by ptrnull** [comment]
@dhellmann @russellb  can you ltgm and/or approve?

**Pull request merged**
