### PR TITLE
Update owners to reflect team changes

### PR DESCRIPTION
**Pull request by codificat**
To  complement #183 : there have been some changes in the community team at RH and former website maintainers moved to another group.

For this change to work I should be part of the org (not there at the moment)

### CODE REVIEW

**Comment by russellb** [comment]
Sent org invite, go to https://github.com/metal3-io to accept.  Then make your membership public

**Comment by codificat** [comment]
Thanks, done. Let's see if now we can
/verify-owners

**Comment by russellb** [comment]
/approve

@dhellmann

**Comment by codificat** [comment]
closed by mistake, reopening

**Pull request merged**
