### PR TITLE
Post: Scaling part 1

### PR DESCRIPTION
**Pull request by lentzi90**
Add post about scalability. This is the first part in a series of blog posts and focuses on BMO test mode.

Also updates .gitignore and pre-commit config

### CODE REVIEW

**Review by mboukhalfa — COMMENTED** [review]
lgtm some comments here I also think it will be good if you can give full steps scenario for scalling to 1000 in the intro before starting focusing on bmo test mode

**Comment by lentzi90** [comment]
Thanks for the review @mboukhalfa ! I think I have addressed all comments, PTAL :slightly_smiling_face:

**Review by tuminoid — APPROVED** [review]
LGTM. Good work, we havent't had a new blog post in a long time.

**Review by mboukhalfa — APPROVED** [review]

**Comment by lentzi90** [comment]
Could you please approve this @hroyrh ?

**Pull request merged**
