### PR TITLE
include social media icon links in footer, remove few buttons from community resource page

### PR DESCRIPTION
**Pull request by hroyrh**
Added social media and community resources' icons to the footer, and removed the operaterhub.io and rook.io buttons from the community resources page.

### CODE REVIEW

**Comment by hroyrh** [comment]
Fixes #193

**Comment by fmuyassarov** [comment]
> Fixes #193
> cc @fmuyassarov
> I have added several icons to the footer including a github icon pointing to metal3-io github project page. Do you think its sufficient or should I add another explicit link/button to the main page?


Thanks @hroyrh , logos look nice.  I think the current state is good enough. 
What do you think about making those logos little bit bigger or align to the center?

**Comment by hroyrh** [comment]
@fmuyassarov I have increased the icon size, let me know how it looks.

**Comment by fmuyassarov** [comment]
Thanks @hroyrh. It looks good me.
/lgtm

**Comment by russellb** [comment]
It looks like the travis CI job needs to be fixed first.

**Comment by hroyrh** [comment]
@fmuyassarov do I need to rebase this PR to add the ci fix or are we good to go

**Comment by fmuyassarov** [comment]
> @fmuyassarov do I need to rebase this PR to add the ci fix or are we good to go

I think we need a rebase, because I assume we won't able to merge it even with lgtm+approve until all the CI checks passed.

**Comment by fmuyassarov** [comment]
> > @fmuyassarov do I need to rebase this PR to add the ci fix or are we good to go
> 
> I think we need a rebase, because I assume we won't able to merge it even with lgtm+approve until all the CI checks passed.

Or you can just push empty commit with --amend.

**Comment by dhellmann** [comment]
@hroyrh if you make your membership in the metal3-io GitHub org public, the bot will respond to your instructions. Right now it can't tell if you're a trusted person because it does not have admin rights to see the private org membership list. https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership

**Comment by hroyrh** [comment]
@dhellmann thanks! can you also take some time to see if this PR looks good

**Pull request merged**
