### PR TITLE
Fixed grammatical, punctuation and spelling errors in markdown files

### LINKED ISSUE #284: Fix grammatical, punctuation and spelling errors in the documentation
The goal for this issue is to:

- Check markdown files for any errors in grammar, punctuation or spelling and fix these errors.

### PR DESCRIPTION
**Pull request by iamatifmoin**
Closes #284

- I have made changes to the markdown files to fix grammatical, punctuation and spelling errors.

- This is a minor contribution and I am working towards making more significant contributions to the project in the future.

### CODE REVIEW

**Review by tuminoid — COMMENTED** [review]
Thanks a lot for the contribution! Can you please squash your commits into one?

**Comment by tuminoid** [comment]
/lgtm cancel

Squashing needed.

**Comment by iamatifmoin** [comment]
> Thanks a lot for the contribution! Can you please squash your commits into one?

Sure! 
I have squashed all changes into commit 2cd45b74856d86886c0390db460e4ceb6f6ce47e

**Comment by tuminoid** [comment]
> > Thanks a lot for the contribution! Can you please squash your commits into one?
> 
> Sure! I have squashed all changes into commit [2cd45b7](https://github.com/metal3-io/metal3-io.github.io/commit/2cd45b74856d86886c0390db460e4ceb6f6ce47e)

You now have 6 commits instead of 4 in this PR. Please try again.

**Comment by iamatifmoin** [comment]
@tuminoid 
I think I have fixed it now.

**Review by tuminoid — APPROVED** [review]
Yes, now its all single commit. Thanks for the contribution.

/lgtm

**Review by lentzi90 — COMMENTED** [review]
Thank you very much for this!
/approve

I saw a few changes that may not be necessary. Specifically changing of American English to British English (e.g. `center` -> `centre`, `color` -> `colour`). Not sure if we have a preference for that really, so it may be unnecessary to do those changes. But this contains so much good that I would rather take it in directly.

**Comment by iamatifmoin** [comment]
> Thank you very much for this! /approve
> 
> I saw a few changes that may not be necessary. Specifically changing of American English to British English (e.g. `center` -> `centre`, `color` -> `colour`). Not sure if we have a preference for that really, so it may be unnecessary to do those changes. But this contains so much good that I would rather take it in directly.

Thank you for the approval.

If it is really necessary to revert the changes, I could either:
- Add another commit removing those changes, then squash
- Revert the changes in a new PR

What do you suggest? I think I should go for the latter.

Also, I want to work on this project under Outreachy and I am trying to improve my application to get selected. 
Since you are a member of the project, can you please direct me towards some issues I could work on or help with?

**Comment by lentzi90** [comment]
No need to revert anything. This should be already merged but the CI is acting up...
/retest all

**Comment by tuminoid** [comment]
Out of ideas what's wrong with tide here, I'm going to merge it manually.

**Pull request merged**
