### PR TITLE
added section opening tag

### PR DESCRIPTION
**Pull request by chukwunnonso**
There is no opening section tag on the documentation.html. I have added it. 

/assign @hroyrh

### CODE REVIEW

**Comment by hroyrh** [comment]
@chukwunnonso thank you for the PR! , and apologies for the late response. 
This looks good to me.
/lgtm

**Comment by tuminoid** [comment]
/hold 

Tide is stuck.

**Comment by tuminoid** [comment]
Tide is a mess, merged manually. Thanks for the contribution!

**Pull request merged**
