### PR TITLE
Update OWNERS to reflect team changes

### PR DESCRIPTION
**Pull request by codificat**
Due to a job change I am not going to be active here for the time being, so this PR is to remove myself as an active approver in this repo.

@hroyrh will continue with tasks from my previous team, and that's why I'm adding him here as a replacement in the same change.

If it's preferred to just remove myself and follow the [process to add a new maintainer](https://github.com/metal3-io/metal3-docs/blob/master/maintainers/README.md) instead just let me know and I will limit the change to myself.

Thanks! :wave:

### CODE REVIEW

**Comment by dhellmann** [comment]
@codificat Thank you for all of your contributions and for managing this transition smoothly.

Since @hroyrh is an existing contributor to this repo and member of the org, I'm OK with both changes coming in the same PR.

/approve

**Comment by fmuyassarov** [comment]
Hi @codificat ,
Would you mind to rebase this PR? @iranzo helped us to put a fix, and if you rebase we should be able to pass the Travis and get this PR merged.

**Comment by iranzo** [comment]
I've rebased it

**Comment by fmuyassarov** [comment]
@dhellmann Would you mind to lgtm if looks okay?

**Pull request merged**
