### PR TITLE
Reflect the change of ssh username to metal3 for all images

### PR DESCRIPTION
**Pull request by hroyrh**
I have updated the ssh_username to "metal3" wherever required, and this applies for all the image types.

### CODE REVIEW

**Comment by hroyrh** [comment]
@alosadagrande can you review this ?

**Comment by dhellmann** [comment]
I'm not familiar with the changes that modified the username in the images. What controls that? Is it a default in metal3-dev-env somewhere? Or do we have some custom images?

**Comment by hroyrh** [comment]
@dhellmann this is to reflect the changes made in this [PR](https://github.com/metal3-io/metal3-dev-env/pull/300). The new user has been added to the clusterctl env file template and now makes the `ssh_username=metal3` for both all the supported distros.

**Comment by dhellmann** [comment]
Thanks for the link @hroyrh 

/lgtm

**Pull request merged**
