### PR TITLE
Document custom hostnames

### PR DESCRIPTION
**Pull request by cybertron**
Add documentation of the custom hostname feature from https://github.com/metal3-io/metal3-dev-env/pull/238

Also fix a small issue in the readme.

### CODE REVIEW

**Comment by iranzo** [comment]
Putting this on 
/hold

https://github.com/metal3-io/metal3-dev-env/pull/238/files gets merged

**Comment by iranzo** [comment]
/lgtm
/approve

For merging once the other one is merged too

**Comment by iranzo** [comment]
Would you mind rebasing so that when the upstream PR is merged we can get this merged too?

Thanks!

**Comment by cybertron** [comment]
Rebased.

**Comment by cybertron** [comment]
Rebased again. Note that the dependency has merged so the hold can be removed.

**Pull request closed without merging**
