### PR TITLE
Addalosada

### PR DESCRIPTION
**Pull request by iranzo**
Adds Alberto to the repo

### CODE REVIEW

**Comment by iranzo** [comment]
@russellb something that I should fix here?

**Comment by iranzo** [comment]
Updated to resolve conflicts

**Comment by iranzo** [comment]
We need to get Alberto added to the organization for this to be considered valid change

**Comment by iranzo** [comment]
@russellb can you add @alosadagrande to the website team so that we've the bot getting this as valid and merge so that he gets automatically reviews?

**Comment by ptrnull** [comment]
@russellb can you merge this manually?

**Comment by iranzo** [comment]
> @russellb can you merge this manually?

Not just merge, also add Alberto to this GH organization

**Comment by russellb** [comment]
Invited to join github org

**Comment by alosadagrande** [comment]
Thanks @russellb, issue can be closed

**Comment by alosadagrande** [comment]
Thanks @russellb, PR needs to be merged then.

**Comment by iranzo** [comment]
@alosadagrande did you accept the invite?

**Comment by alosadagrande** [comment]
Yes I did.

**Comment by iranzo** [comment]
@alosadagrande @russellb there seems to be some problem still as the bot can't detect it.

Thanks

**Comment by iranzo** [comment]
sorry, closed by error

**Comment by russellb** [comment]
> @alosadagrande @russellb there seems to be some problem still as the bot can't detect it.
> 
> Thanks

You need to make your membership Public. It’s private by default.

**Pull request merged**
