### PR TITLE
Change title color to improve readability

### PR DESCRIPTION
**Pull request by elfosardo**
Also fix a repetition in the sub title

### CODE REVIEW

**Review by tuminoid — COMMENTED** [review]
So this turns turquiosie Metal3 into black Metal3. Since its on the white background, I agree it was not optimal.

/lgtm

**Comment by elfosardo** [comment]
> So this turns turquiosie Metal3 into black Metal3. Since its on the white background, I agree it was not optimal.
> 
> /lgtm

being a fan of Black Metal I waited even too long to change this :D

**Review by lentzi90 — COMMENTED** [review]
/approve

**Pull request merged**
