### PR TITLE
yolanda's shift dev video blogpost

### PR DESCRIPTION
**Pull request by ptrnull**
Signed-off-by: Pedro Ibáñez <pedro@redhat.com>

Blog post about the video of Yolanda Robla, a presentation about Metal3 made in the Shift Dev event in Croatia.

To publish during January 20th.

### CODE REVIEW

**Comment by ptrnull** [comment]
@russellb @yrobla @dhellmann @stbenjam can you review, please? should be publish next Monday, thanks!
/hold

**Comment by iranzo** [comment]
/hold cancel
@russellb can we get /lgtm to get it merged ?

**Comment by iranzo** [comment]
As it was given previously, adding 

/lgtm

again

**Pull request merged**
