### PR TITLE
Reflect refactoring changes in metal3-dev-env

### PR DESCRIPTION
**Pull request by maelk**
https://github.com/metal3-io/metal3-dev-env/pull/403

### CODE REVIEW

**Comment by fmuyassarov** [comment]
@maelk Shall we unhold it and move forward as [#403](https://github.com/metal3-io/metal3-dev-env/pull/403 ) merged now?

**Comment by maelk** [comment]
/hold cancel
Yes, good to go, thanks

**Comment by fmuyassarov** [comment]
@maelk would you mind to rebase your branch please?

**Comment by maelk** [comment]
done, thank you

**Comment by furkatgofurov7** [comment]
Travis CI is failing in #185 , #186  and #190 with the [same error(path issues)](https://travis-ci.org/github/metal3-io/metal3-io.github.io/builds/722742603) and this PR should solve it once it is merged.

**Comment by maelk** [comment]
@russellb or @dhellmann would you mind approving this PR if it is ok for you ?

**Review by dhellmann — COMMENTED** [review]
These paths look correct to me.

/approve

**Pull request merged**
