### PR TITLE
footer: Add Linux Foundation footer

### PR DESCRIPTION
**Pull request by russellb**
As requested on https://github.com/cncf/toc/issues/532

### CODE REVIEW

**Comment by codificat** [comment]
> As requested on [cncf/toc#532](https://github.com/cncf/toc/issues/532)

I see... well, the content is fine, but so much text is maybe a bit too big? Maybe we could add this modification to the style:
```diff
diff --git a/_sass/_footer.scss b/_sass/_footer.scss
index 3b2f9d4..d61bf97 100644
--- a/_sass/_footer.scss
+++ b/_sass/_footer.scss
@@ -1,4 +1,5 @@
 .mk-main-footer {
     border-top: var(--mk--BorderWidth--sm) solid var(--mk--BorderColor--300);
+    font-size: var(--mk--FontSize--xs);
     padding: var(--mk--spacer--lg) var(--mk--spacer--md);
 }
```

WDYT? I tested it locally and it looks a bit better to me...

**Comment by russellb** [comment]
@codificat thanks for the tip!  I've included that change.  Let's see how the netlify preview looks now ...

**Comment by russellb** [comment]
> @codificat thanks for the tip! I've included that change. Let's see how the netlify preview looks now ...

yes, that looks better to me!  thanks again

**Comment by codificat** [comment]
Cool. Ship it.

/lgtm
/approve

**Pull request merged**
