### PR TITLE
Update try-it

### PR DESCRIPTION
**Pull request by maelk**
- change master-0 and worker-0 to node-0 and node-1
- add CAPI_VERSION

### CODE REVIEW

**Comment by maelk** [comment]
This is linked to https://github.com/metal3-io/metal3-dev-env/pull/153

**Comment by ptrnull** [comment]
/lgtm
@russellb / @dhellmann can you check?

**Comment by maelk** [comment]
I will add the v1alpha2 instructions in this PR too, it should come together, otherwise we would have people following the try-it that is still v1alpha1 deploying with v1alpha2 without knowing it.

**Comment by russellb** [comment]
"  *  linking to internal hash #provisioning-a-machine that does not exist (line 95)" -- CI failure

**Pull request merged**
