### PR TITLE
Add post about mixed cluster with BYOH and Metal3

### PR DESCRIPTION
**Pull request by lentzi90**
The changes to the pre-commit config is the same as in https://github.com/metal3-io/metal3-io.github.io/pull/234 and was needed to make it pass pre-commit.

The blog post has some large code snippets that I'm not very happy with. Do you have any suggestions for how to "hide" them? Can I add them somewhere in the repo and link to them? Perhaps in `assets`?

### CODE REVIEW

**Review by fmuyassarov — COMMENTED** [review]
This is awesome! For hiding the code blocks perhaps we can use something like this?

<details>
<summary style="font-size:14px">Click here to see the code</summary>
<p>

```yaml
your code block
```
</p></details>

**Comment by fmuyassarov** [comment]
> This is awesome! For hiding the code blocks perhaps we can use something like this?
> 
> Click here to see the code

Here is the actual code that makes it: https://gist.github.com/fmuyassarov/286bde5659c2fff8870056be4ef77d57
I could not paste it here because Github shows it already in rendered format.

**Review by fmuyassarov — COMMENTED** [review]
One minor thing I would suggest is to add the output of [`clusterctl describe cluster`](https://cluster-api.sigs.k8s.io/clusterctl/commands/describe-cluster.html) command. It gives nice overview of CAPI cluster.

**Comment by lentzi90** [comment]
Thanks @fmuyassarov for the excellent suggestions! I made some of the code blocks folded and also added the clusterctl describe output at the end. PTAL

**Review by fmuyassarov — APPROVED** [review]

**Comment by lentzi90** [comment]
Made a change to the conclusion section since I had forgotten about the EKS control plane provider.

**Pull request merged**
