### PR TITLE
fix broken link and ignore twitter 400 error during ci testing

### PR DESCRIPTION
**Pull request by hroyrh**
Removed section from `Metal3` blog post which had a broken link, since its no longer relevant. And ignored twitter urls so that ci-testing doesn't break.

### CODE REVIEW

**Comment by hroyrh** [comment]
@fmuyassarov can you take a look at this, it might help fix the ci failures in the other pending PRs

**Comment by fmuyassarov** [comment]
In #198 I see from the [Travis](https://travis-ci.org/github/metal3-io/metal3-io.github.io/builds/751810661) output that it is failing due incorrect URLs for twitter & a script in openshift

```
- ./_site/blog/2019/06/25/Metal3.html

  *  External link https://github.com/openshift-metal3/dev-scripts/blob/master/link-machine-and-node.sh failed: 404 No error

- ./_site/blog/2019/10/31/OpenStack-Ironic-and-Bare-Metal-Infrastructure_All-Abstractions-Start-Somewhere.html

  *  External link https://twitter.com/ashinclouds failed: 400 No error

  *  External link https://twitter.com/hogepodge failed: 400 No error

- ./_site/blog/2019/12/04/Introducing_metal3_kubernetes_native_bare_metal_host_management.html

  *  External link http://twitter.com/doughellmann failed: 400 No error

  *  External link https://twitter.com/intent/tweet?text=Introducing%20Metal3:%20Kubernetes%20Native%20Bare%20Metal%20Host%20Management%20-%20Russell%20Bryant%20&%20Doug%20Hellmann,%20Red%20Hat%20-%20KubeCon%20NA,%20November%202019&url=blog/2019/12/04/Introducing_metal3_kubernetes_native_bare_metal_host_management.html failed: 400 No error

  *  External link https://twitter.com/metal3_io failed: 400 No error

- ./_site/blog/2020/07/06/IP_address_manager.html

  *  External link https://twitter.com/intent/tweet?text=Introducing%20the%20Metal3%20IP%20Address%20Manager&url=blog/2020/07/06/IP_address_manager.html failed: 400 No error
```

Since this is a blocker for other PRs, I'm fine with the changes. However, I don't have rights to give lgtm in this repo.
Tagging /cc @russellb  here to have a look.

**Pull request merged**
