### PR TITLE
remove yaspeller

### PR DESCRIPTION
**Pull request by tuminoid**
Combined that yaspeller does not work (#378 #379 #380) and how yaspeller works that it is uploading all the content to Russia into Yandex API for spellcheck. This could lead to leaking of sensitive information. Remove it.

TODO: find another spellcheck tool later.

### CODE REVIEW

**Review by lentzi90 — COMMENTED** [review]
Not sure what sensitive content it would upload that wouldn't anyway be published on github or a webpage, but it is a pain...
/approve

**Comment by tuminoid** [comment]
> Not sure what sensitive content it would upload that wouldn't anyway be published on github or a webpage, but it is a pain... /approve

Not an issue when its running in CI obviously, but running locally, you might end up sending over files you shouldn't. The defaults of course are not dangerous, but you can feed it any file, bad pattern etc.

**Comment by tuminoid** [comment]
> Should we find a replacement first?

It doesn't work, so it is only a risk right now. We can find alternative later.

**Review by Rozzii — APPROVED** [review]
/lgtm

**Pull request merged**
