### PR TITLE
Update setup to include make clean

### PR DESCRIPTION
**Pull request by mkth1**

### CODE REVIEW

**Comment by russellb** [comment]
This sounds like a bug we should fix. What led to this suggestion?

**Comment by mkth1** [comment]
@russellb I noticed, If i try to re-run `make` without `make clean` then it fails with message

```sh
device provisioning already exists; can't create bridge with the same name
Makefile:7: recipe for target 'configure_host' failed
```
Therefore, in order to avoid this, i updated the instruction with `make clean; make` in case of re-run

**Comment by russellb** [comment]
How about we try to make metal3-dev-env detect this and give a suggestion to run "make clean"?

**Comment by mkth1** [comment]
@russellb sounds good, will do it in metal3-dev-env

**Comment by russellb** [comment]
Thanks!

**Pull request closed without merging**
