### PR TITLE
updates

### LINKED ISSUE #51: Foot notes should be separated from text
imagen

### PR DESCRIPTION
**Pull request by matthewcarleton**
Closes #51 #49 #52 
Might fix scroll issue. Need to confirm browser.

### CODE REVIEW

**Comment by iranzo** [comment]
imagen


From: https://deploy-preview-54--metal3.netlify.com/blog/2019/04/30/metal-kubed-baremetal-provisioning-for-kubernetes

**Comment by iranzo** [comment]
Would it be possible to put the scrollbar on the 'blockquote' or the 'codeblock' as the remaining text should be always able to reflow?

With that approach the scroll bar in the lower level will not appear, but only for the blocks (if interested to read them)


This is what I'm referring to:

image

**Comment by matthewcarleton** [comment]
gotcha, see it now @iranzo

**Comment by iranzo** [comment]
Much better like this! Cool!! Thanks!!

**Pull request merged**
